Module CalcBoard
    Public Sub Draw()
        Console.WriteLine("   ╔═══════════════╗")
        Console.WriteLine("   ║               ║")
        Console.WriteLine("   ║═══════════════║")
        Console.WriteLine("   ║ 0             ║")
        Console.WriteLine("   ║═══════════════║")
        Console.WriteLine("   ║  C    CE    < ║")
        Console.WriteLine("   ║═══╦═══╦═══╦═══║")
        Console.WriteLine("   ║ 7 ║ 8 ║ 9 ║ / ║")
        Console.WriteLine("   ╠═══╬═══╬═══╬═══╣")
        Console.WriteLine("   ║ 4 ║ 5 ║ 6 ║ x ║")
        Console.WriteLine("   ╠═══╬═══╬═══╬═══╣")
        Console.WriteLine("   ║ 1 ║ 2 ║ 3 ║ - ║")
        Console.WriteLine("   ╠═══╬═══╬═══╬═══╣")
        Console.WriteLine("   ║ ¬ ║ 0 ║ . ║ + ║")
        Console.WriteLine("   ╚═══╩═══╩═══╩═══╝")
        Console.WriteLine()
    End Sub
End Module
